/**
 * Config Writer — generates .llm_config.yaml for each pipeline run
 * based on the user's command flags and quality preset.
 */
import { writeFileSync } from 'fs';
import path from 'path';
import YAML from 'yaml';
import { PipelineOptions } from '../types/pipeline.js';

/**
 * Generate and write .llm_config.yaml.
 *
 * Writes to the given target directory. If consortiumDir is also provided
 * (and different from targetDir), writes a copy there too — the consortium
 * loads config from CWD, which is still the consortium root.
 *
 * @param targetDir - Primary target (run directory for archival).
 * @param options - Resolved pipeline options.
 * @param consortiumDir - Optional: also write to consortium root for CWD loading.
 */
export function writeConfig(
  targetDir: string,
  options: PipelineOptions,
  consortiumDir?: string,
): void {
  const config: Record<string, any> = {
    // Main agent model
    main_agents: {
      model: options.model,
      reasoning_effort: 'high',
      budget_tokens: 128000,
    },

    // Experiment tool models (match main model for consistency)
    run_experiment_tool: {
      code_model: options.model,
      feedback_model: options.model,
      vlm_model: options.model,
      report_model: options.model,
    },

    // Budget — strict enforcement
    budget: {
      usd_limit: options.budgetUsd,
      hard_stop: true,
      fail_closed: true,
    },

    // Counsel mode
    counsel: {
      enabled: options.enableCounsel,
      max_debate_rounds: options.counselMaxDebateRounds,
      synthesis_model: 'claude-sonnet-4-6',
      ...(options.enableCounsel
        ? {
            models: [
              {
                model: 'claude-opus-4-6',
                reasoning_effort: 'high',
              },
              {
                model: 'gpt-5.4',
                reasoning_effort: 'high',
                verbosity: 'high',
              },
              {
                model: 'gemini-3-pro-preview',
                thinking_budget: 65536,
              },
            ],
          }
        : {}),
    },

    // Persona council
    persona_council: {
      max_debate_rounds: options.personaDebateRounds,
      synthesis_model: options.model,
    },

    // Duality check
    duality_check: {
      model: options.model,
    },
  };

  const yamlContent = [
    '# Auto-generated by pAI/MSc-openclaw plugin',
    `# Preset: ${options.preset} | Model: ${options.model} | Budget: $${options.budgetUsd}`,
    `# Generated at: ${new Date().toISOString()}`,
    '',
    YAML.stringify(config),
  ].join('\n');

  // Write to target directory (run dir — for archival)
  const configPath = path.join(targetDir, '.llm_config.yaml');
  writeFileSync(configPath, yamlContent);

  // Also write to consortium root if provided (for CWD-based loading)
  if (consortiumDir && consortiumDir !== targetDir) {
    const consortiumConfigPath = path.join(consortiumDir, '.llm_config.yaml');
    writeFileSync(consortiumConfigPath, yamlContent);
  }
}
