/**
 * API Key Passthrough — reads API keys from the OpenClaw gateway's
 * environment and writes them to the consortium's .env file.
 *
 * This is the core UX win: users configure API keys once in OpenClaw,
 * and the plugin automatically passes them to the Python backend.
 *
 * Re-written on every run invocation to pick up key rotations.
 */
import { writeFileSync } from 'fs';
import path from 'path';

/**
 * Map of OpenClaw env var names to consortium .env var names.
 * In most cases they're identical, but this map allows for future divergence.
 */
const KEY_MAP: Record<string, string> = {
  // LLM provider keys
  ANTHROPIC_API_KEY: 'ANTHROPIC_API_KEY',
  OPENAI_API_KEY: 'OPENAI_API_KEY',
  GOOGLE_API_KEY: 'GOOGLE_API_KEY',
  OPENROUTER_API_KEY: 'OPENROUTER_API_KEY',
  DEEPSEEK_API_KEY: 'DEEPSEEK_API_KEY',
  XAI_API_KEY: 'XAI_API_KEY',

  // Search/web tools
  SERPER_API_KEY: 'SERPER_API_KEY',
  SEARXNG_INSTANCE_URL: 'SEARXNG_INSTANCE_URL',

  // GPU training (Tinker mode)
  TINKER_API_KEY: 'TINKER_API_KEY',

  // Observability (optional)
  LANGCHAIN_API_KEY: 'LANGCHAIN_API_KEY',
};

/** Provider keys that are sufficient to run the pipeline. */
const PROVIDER_KEYS = [
  'ANTHROPIC_API_KEY',
  'OPENAI_API_KEY',
  'GOOGLE_API_KEY',
  'OPENROUTER_API_KEY',
  'DEEPSEEK_API_KEY',
  'XAI_API_KEY',
];

/**
 * Write .env file in the given directory with all available API keys.
 *
 * @param targetDir - Directory to write .env to (run dir or consortium dir).
 * @returns Array of provider names that have keys configured.
 * @throws Error if no provider keys are found at all.
 */
export function writeEnvFile(targetDir: string): string[] {
  const lines: string[] = [
    '# Auto-generated by pAI/MSc-openclaw plugin',
    `# Written at: ${new Date().toISOString()}`,
    '# Do not edit — this file is overwritten on every run.',
    '',
  ];

  const configuredProviders: string[] = [];

  for (const [envVar, dotenvVar] of Object.entries(KEY_MAP)) {
    const value = process.env[envVar];
    if (value) {
      lines.push(`${dotenvVar}=${value}`);
      if (PROVIDER_KEYS.includes(envVar)) {
        configuredProviders.push(envVar.replace('_API_KEY', '').toLowerCase());
      }
    }
  }

  if (configuredProviders.length === 0) {
    throw new Error(
      'No LLM API keys found in your environment. ' +
        'Configure at least one of these in your OpenClaw settings:\n' +
        PROVIDER_KEYS.map((k) => `  - ${k}`).join('\n'),
    );
  }

  // Add consortium-specific env vars
  lines.push('');
  lines.push('# Pipeline configuration');
  lines.push('LITELLM_LOG=WARNING');

  const envPath = path.join(targetDir, '.env');
  writeFileSync(envPath, lines.join('\n') + '\n');

  return configuredProviders;
}

/**
 * Build the full subprocess environment for a pipeline run.
 *
 * Combines the current process environment with:
 * - All available API keys (explicitly set, not relying on .env file)
 * - PYTHONUNBUFFERED=1 for real-time stdout parsing
 * - LITELLM_LOG=WARNING to reduce noise
 * - REFERENCE_FILES_DIR pointing to uploads (if any files were uploaded)
 *
 * Also writes a .env file to the run directory for consortium's dotenv.load_dotenv().
 *
 * @param runDir - The run workspace directory.
 * @param uploadsDir - Path to initial_context/uploads/ (optional).
 * @returns Complete environment object for spawn().
 */
export function buildSubprocessEnv(
  runDir: string,
  uploadsDir?: string,
): NodeJS.ProcessEnv {
  // Write .env to the run directory
  writeEnvFile(runDir);

  // Build subprocess env with explicit key values
  const env: NodeJS.ProcessEnv = {
    ...process.env,
    PYTHONUNBUFFERED: '1',
    LITELLM_LOG: 'WARNING',
  };

  // Explicitly pass all API keys so the subprocess doesn't depend on .env loading
  for (const [envVar] of Object.entries(KEY_MAP)) {
    const value = process.env[envVar];
    if (value) {
      env[envVar] = value;
    }
  }

  // Point to uploaded reference files if any exist
  if (uploadsDir) {
    env.REFERENCE_FILES_DIR = uploadsDir;
  }

  return env;
}

/**
 * Check which provider keys are available without writing anything.
 */
export function getAvailableProviders(): string[] {
  return PROVIDER_KEYS.filter((k) => !!process.env[k]).map((k) =>
    k.replace('_API_KEY', '').toLowerCase(),
  );
}

/**
 * Check if counsel mode is possible (requires 3 providers).
 */
export function canUseCounsel(): boolean {
  const providers = getAvailableProviders();
  return (
    providers.includes('anthropic') &&
    providers.includes('openai') &&
    providers.includes('google')
  );
}
